apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    component: frontend
    tier: frontend
spec:
  targetType: ip
  serviceRef:
    name: frontend # route traffic to the awesome-service
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:717188664763:targetgroup/roboshop-dev-frontend/a5ac25fac108d2bd
